---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - 'missing input "PATH" which is required by action .+'
